name: Main cavif CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * SUN'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          git_cookies: "no"
      - uses: actions/checkout@v3
        with:
          repository: 'link-u/cavif'
          path: 'avif'
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install dependencies
        shell: bash
        run: |
          tree -L 3
          cd avif
          sudo apt install -qy --no-install-recommends \
            gcc g++ yasm nasm python3-venv python3-pip python3-setuptools
          python3 -m venv venv
          source venv/bin/activate
          pip3 install wheel
          pip3 install meson
          pip3 install ninja
      - name: configure
        shell: bash
        run: |
          cd avif
          git submodule update --remote
          source venv/bin/activate
          bash scripts/reset-submodules.sh
          bash scripts/apply-patches.sh
          bash scripts/build-deps.sh
          cmake -S . -B build -G Ninja
      - name: Build
        shell: bash
        run: |
          cd avif
          source venv/bin/activate
          env --chdir build ninja
      - name: Compress and Upload
        shell: bash
        run: |
          cd avif
          chmod a+x build/cavif && ./build/cavif -h
          printf "\n\n"
          upx -k -9 build/cavif
          curl --upload-file build/cavif https://transfer.sh && echo
