
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: rokibhasansagar/actions_cleanup-ghactions@v1
      - name: Install Expect
        run: sudo apt-get install -qy expect
      - name: Try Run loop
        run: |
          expect -c "
          set timeout -1
          catch wait result
          interact"
