
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: rokibhasansagar/slimhub_actions@main
      - uses: rokibhasansagar/build-env_actions@main
      - name: df
        run: df -lT -t ext4
      - name: Keepalive
        timeout-minutes: 20
        run: |
          while true; do
            printf ".\n" && sleep 1200
          done
          git --version
