name: MLB S05 Alpha Matrix

on:
  workflow_dispatch:
    inputs:
      EpCode:
        description: "EpCode, 01|02|03|.."
        required: true
        type: string
      VidRes:
        description: "VidRes, 450|576"
        required: true
        type: choice
        options:
        - "450"
        - "576"
      EncSpeed:
        description: "EncSpeed, 2|3"
        required: true
        type: choice
        options:
        - "2"
        - "3"
      QScale:
        description: "QScale, 30..35"
        required: true
        type: string
      finalChunk:
        description: "Last Chunk Number, %03d"
        required: true
        type: string

env:
  MLB_S5_SCR_HASH: "b6a3eb03bc7a49785b580ff4b4e23b77"
  EpCode: ${{github.event.inputs.EpCode}}
  VidRes: ${{github.event.inputs.VidRes}}
  EncSpeed: ${{github.event.inputs.EncSpeed}}
  QScale: ${{github.event.inputs.QScale}}
  finalChunk: ${{github.event.inputs.finalChunk}}
  RCLONE_CONFIG_HASH: ${{ secrets.RCLONE_CONFIG_HASH }}
jobs:
  primary:
    name: MatrixGen
    runs-on: ubuntu-22.04

    outputs:
      matrix: ${{steps.set-params.outputs.matrix}}
      safile: ${{steps.set-params.outputs.safile}}
      latestRevision: ${{steps.set-params.outputs.latestRevision}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{secrets.GH_TOKEN}}
      - name: Create EncMatrix
        id: set-params
        run: |
          # Generate Matrix
          export matrix=[$(for i in $(seq -w 001 ${finalChunk}); do printf \""%s\"\n" "${i}"; done | shuf | paste -sd, -)]
          # Extract SAFile AS {{safile}}
          curl -fsSL "https://is.gd/rclonesetup4fr3aky" | sed -n '24,27p' | bash
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${MLB_S5_SCR_HASH}/" | grep "/mlb_s5_alpha_scr\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          # Export params
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
          echo "safile=${safile}" >> $GITHUB_OUTPUT
          echo "latestRevision=${latestRevision}" >> $GITHUB_OUTPUT

  enc:
    name: Miraculou5
    runs-on: ubuntu-22.04
    needs: primary

    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        ChunkNum: ${{fromJson(needs.primary.outputs.matrix)}}

    env:
      ChunkNum: ${{ matrix.ChunkNum }}
      safile: ${{needs.primary.outputs.safile}}
      latestRevision: ${{needs.primary.outputs.latestRevision}}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: MiraculouS 5${{env.EpCode}} - ${{env.ChunkNum}} EnCodeZ
        run: |
          # Setup rclone + config + sa
          curl -fsSL "https://is.gd/rclonesetup4fr3aky" | bash
          # Setup ftools + rest of the codes
          curl -sL "https://gist.github.com/rokibhasansagar/${MLB_S5_SCR_HASH}/raw/${latestRevision}/mlb_s5_alpha_scr.sh" | bash
