name: MLB S05 Alpha Matrix

on:
  workflow_dispatch:
    inputs:
      ScrUrl:
        description: "mlb_s5_alpha_scr_url"
        required: true
        type: string
      EpCode:
        description: "EpCode, 01|02|03"
        required: true
        type: string
      VidRes:
        description: "VidRes, 450|576"
        required: true
        type: choice
        options:
        - "450"
        - "576"
      EncSpeed:
        description: "EncSpeed, 2|3"
        required: true
        type: choice
        options:
        - "2"
        - "3"
      QScale:
        description: "QScale, 30..35"
        required: true
        type: string
      finalChunk:
        description: "Last Chunk Number, %03d"
        required: true
        type: string

env:
  mlb_s5_alpha_scr_url: ${{github.event.inputs.ScrUrl}}
  EpCode: ${{github.event.inputs.EpCode}}
  VidRes: ${{github.event.inputs.VidRes}}
  EncSpeed: ${{github.event.inputs.EncSpeed}}
  QScale: ${{github.event.inputs.QScale}}
  finalChunk: ${{github.event.inputs.finalChunk}}
  RCLONE_CONFIG_URL: ${{secrets.RCLONE_CONFIG_URL}}

jobs:
  primary:
    name: MatrixGen
    runs-on: ubuntu-22.04

    outputs:
      matrix: ${{steps.set-params.outputs.matrix}}
      safile: ${{steps.set-params.outputs.safile}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{secrets.GH_TOKEN}}
      - name: Create EncMatrix
        id: set-params
        run: |
          export matrix=[$(for i in $(seq -w 001 ${finalChunk}); do printf \""%s\"\n" "${i}"; done | shuf | paste -sd, -)]
          git clone -q --filter=blob:none https://github.com/rokibhasansagar/RcloneSA4Phantom
          mkdir -p /tmp/service_accounts && mv RcloneSA4Phantom/accounts/*.json /tmp/service_accounts/
          export safile=$(ls /tmp/service_accounts/*.json | shuf -n 1)
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
          echo "safile=${safile}" >> $GITHUB_OUTPUT

  enc:
    name: Miraculou5
    runs-on: ubuntu-22.04
    needs: primary

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        ChunkNum: ${{fromJson(needs.primary.outputs.matrix)}}

    env:
      ChunkNum: ${{ matrix.ChunkNum }}
      safile: ${{needs.primary.outputs.safile}}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: MiraculouS 5${{env.EpCode}} - ${{env.ChunkNum}} EnCodeZ
        run: |
          curl -sL "${mlb_s5_alpha_scr_url}" | bash
