name: OmniSplitterZ

on:
  workflow_dispatch:
    inputs:
      AniCode:
        description: AniCode
        required: true
        type: string
      AniName:
        description: AniName
        required: true
        type: string
      RelFormat:
        description: RelFormat
        required: true
        type: string
      MediaFolder:
        description: MediaFolder
        required: true
        type: string
      MediaFilterX:
        description: MediaFilterX
        required: true
        type: string
      OptionalParams:
        description: OptionalParams (pipe-separated, url-encoded)
        required: false
        type: string
        default: ""

env:
  Script_Gist_Hash: "0e0aa3ed50f14cc45aba6b6b9c87a349"
  Script: "OmniSplitterZ.sh"
  AniCode: ${{ github.event.inputs.AniCode }}
  AniName: ${{ github.event.inputs.AniName }}
  RelFormat: ${{ github.event.inputs.RelFormat }}
  MediaFolder: ${{ github.event.inputs.MediaFolder }}
  MediaFilterX: ${{ github.event.inputs.MediaFilterX }}
  OptionalParams: ${{ github.event.inputs.OptionalParams }}

jobs:
  omni:
    name: OmniSplitterZ
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Run Script
        run: |
          if [[ ${OptionalParams} != '' ]]; then
            for i in $(sed 's/|/\n/g' <<<"${OptionalParams}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(awk -F'=' '{print $2}' <<<"${i}" | sed 's#"##g')
              echo $v="$w" && export $v=$w
            done
          fi
          unset v w 2>/dev/null || true
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${Script_Gist_Hash}/" | grep "/OmniSplitterZ\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          curl -fsSL "https://gist.github.com/rokibhasansagar/${Script_Gist_Hash}/raw/${latestRevision}/${Script}" | bash
