name: H3R0KU APP P1NG3R

on:
  workflow_dispatch:
    inputs:
      APP_URL:
        description: "H3R0KU APP URL 2 P1NG"
        type: string
        required: false
        default: "http://h3r0ku-byp455-mx.herokuapp.com"
      P1NG_MULTIPLIER:
        description: "P1NG3R JOB MULTIPLIER"
        type: number
        required: false
        default: 4

env:
  APP_URL: ${{ github.event.inputs.APP_URL }}
  P1NG_MULTIPLIER: ${{ github.event.inputs.P1NG_MULTIPLIER }}

jobs:
  ping1:
    runs-on: ubuntu-latest

    steps:
      - name: P1NG3R 1
        run: |
          echo -e "Initial ping to TTK Bot"
          curl -sL "${APP_URL}" && echo
          sleep 5m
          for i in {01..30}; do
            echo -e "\nTrying ${i} of 30" 
            curl -sL "${APP_URL}" && echo
            sleep 11m
          done
          echo -e "Final ping to TTK Bot"
          curl -sL "${APP_URL}" && echo
          exit

  ping2:
    runs-on: ubuntu-latest
    if: github.event.inputs.P1NG_MULTIPLIER >= 2
    needs: ping1

    steps:
      - name: P1NG3R 2
        run: |
          echo -e "Secondary ping to TTK Bot"
          sleep 5m
          curl -sL "${APP_URL}" && echo
          sleep 10m
          for i in {01..30}; do
            echo -e "\nTrying ${i} of 30" 
            curl -sL "${APP_URL}" && echo
            sleep 11m
          done
          echo -e "Final ping to TTK Bot"
          curl -sL "${APP_URL}" && echo
          exit

  ping3:
    runs-on: ubuntu-latest
    if: github.event.inputs.P1NG_MULTIPLIER >= 3
    needs: [ping1,ping2]

    steps:
      - name: P1NG3R 3
        run: |
          echo -e "3rd ping to TTK Bot"
          sleep 5m
          curl -sL "${APP_URL}" && echo
          sleep 10m
          for i in {01..30}; do
            echo -e "\nTrying ${i} of 30" 
            curl -sL "${APP_URL}" && echo
            sleep 11m
          done
          echo -e "Final ping to TTK Bot"
          curl -sL "${APP_URL}" && echo
          exit

  ping4:
    runs-on: ubuntu-latest
    if: github.event.inputs.P1NG_MULTIPLIER >= 4
    needs: [ping1,ping2,ping3]

    steps:
      - name: P1NG3R 4
        run: |
          echo -e "4th ping to TTK Bot"
          sleep 5m
          curl -sL "${APP_URL}" && echo
          sleep 10m
          for i in {01..30}; do
            echo -e "\nTrying ${i} of 30" 
            curl -sL "${APP_URL}" && echo
            sleep 11m
          done
          echo -e "Final ping to TTK Bot"
          curl -sL "${APP_URL}" && echo
          exit
