name: Script Matrix CI

on:
  workflow_dispatch:
    inputs:
      ScriptURL:
        description: "Script URL to Run"
        required: true
        type: string
      TotalJobCount:
        description: "Maximum Jobs to Run in Matrix"
        required: true
        default: "4"
        type: choice
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
      RunAsRoot:
        description: "Run As Root?"
        type: boolean
        default: false
        required: false
      Job1CustomVars:
        description: "Custom Vars for Job #1"
        required: false
        type: string
      Job2CustomVars:
        description: "Custom Vars for Job #2"
        required: false
        type: string
      Job3CustomVars:
        description: "Custom Vars for Job #3"
        required: false
        type: string
      Job4CustomVars:
        description: "Custom Vars for Job #4"
        required: false
        type: string
      Job5CustomVars:
        description: "Custom Vars for Job #5"
        required: false
        type: string

env:
  ScriptURL: ${{ github.event.inputs.ScriptURL }}
  RunAsRoot: ${{ github.event.inputs.RunAsRoot }}
  TotalJobCount: ${{ github.event.inputs.TotalJobCount }}

jobs:
  runner_a:
    if: github.event.inputs.TotalJobCount >= '1'
    name: Script Runner 1
    runs-on: ubuntu-22.04
    env:
      Job1CustomVars: ${{ github.event.inputs.Job1CustomVars }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Run Script
        run: |
          if [[ ${Job1CustomVars} != '' ]]; then
            for i in $(sed 's/\s/\n/g' <<<"${Job1CustomVars}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(awk -F'=' '{print $2}' <<<"${i}")
              export $v="$w"
            done
          fi
          if [[ ${RunAsRoot} == true ]]; then
            export executorPrefiv="sudo"
          fi
          curl -fsSL "${ScriptURL}" | ${executorPrefix:-} bash

  runner_b:
    if: github.event.inputs.TotalJobCount >= '2'
    name: Script Runner 2
    runs-on: ubuntu-22.04
    env:
      Job2CustomVars: ${{ github.event.inputs.Job2CustomVars }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Run Script
        run: |
          if [[ ${Job2CustomVars} != '' ]]; then
            for i in $(sed 's/\s/\n/g' <<<"${Job2CustomVars}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(awk -F'=' '{print $2}' <<<"${i}")
              export $v="$w"
            done
          fi
          if [[ ${RunAsRoot} == true ]]; then
            export executorPrefiv="sudo"
          fi
          curl -fsSL "${ScriptURL}" | ${executorPrefix:-} bash

  runner_c:
    if: github.event.inputs.TotalJobCount >= '3'
    name: Script Runner 3
    runs-on: ubuntu-22.04
    env:
      Job3CustomVars: ${{ github.event.inputs.Job3CustomVars }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Run Script
        run: |
          if [[ ${Job3CustomVars} != '' ]]; then
            for i in $(sed 's/\s/\n/g' <<<"${Job3CustomVars}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(awk -F'=' '{print $2}' <<<"${i}")
              export $v="$w"
            done
          fi
          if [[ ${RunAsRoot} == true ]]; then
            export executorPrefiv="sudo"
          fi
          curl -fsSL "${ScriptURL}" | ${executorPrefix:-} bash

  runner_d:
    if: github.event.inputs.TotalJobCount >= '4'
    name: Script Runner 4
    runs-on: ubuntu-22.04
    env:
      Job4CustomVars: ${{ github.event.inputs.Job4CustomVars }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Run Script
        run: |
          if [[ ${Job4CustomVars} != '' ]]; then
            for i in $(sed 's/\s/\n/g' <<<"${Job4CustomVars}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(awk -F'=' '{print $2}' <<<"${i}")
              export $v="$w"
            done
          fi
          if [[ ${RunAsRoot} == true ]]; then
            export executorPrefiv="sudo"
          fi
          curl -fsSL "${ScriptURL}" | ${executorPrefix:-} bash

  runner_e:
    if: github.event.inputs.TotalJobCount == '5'
    name: Script Runner 5
    runs-on: ubuntu-22.04
    env:
      Job5CustomVars: ${{ github.event.inputs.Job5CustomVars }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Run Script
        run: |
          if [[ ${Job5CustomVars} != '' ]]; then
            for i in $(sed 's/\s/\n/g' <<<"${Job5CustomVars}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(awk -F'=' '{print $2}' <<<"${i}")
              export $v="$w"
            done
          fi
          if [[ ${RunAsRoot} == true ]]; then
            export executorPrefiv="sudo"
          fi
          curl -fsSL "${ScriptURL}" | ${executorPrefix:-} bash
