name: Script Runner CI

on:
  workflow_dispatch:
    inputs:
      ScriptURL:
        description: "Script URL to Run"
        required: true
        type: string

env:
  ScriptURL: ${{ github.event.inputs.ScriptURL }}
  FTOOL_ARC_URL2: ${{ secrets.FTOOL_ARC_URL2 }}
  RCLONE_INSTALL_MIRROR: ${{ secrets.RCLONE_INSTALL_MIRROR }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
  PAT: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"

      - name: Rclone and FF Setup
        continue-on-error: true
        run: |
          cd "$(mktemp -d)"
          wget -q "${FTOOL_ARC_URL2}" || curl -sL "${FTOOL_ARC_URL2}" -O
          tar -xJf ff*.tar.xz --strip-components 1
          rm -f bin/*play
          sudo mv bin/* /usr/local/bin/
          curl -sL "${RCLONE_INSTALL_MIRROR}" | sudo bash
          mkdir -p ~/.config/rclone
          curl -sL "${RCLONE_CONFIG_URL}" >~/.config/rclone/rclone.conf
          python3 -m pip install -U yt-dlp
          cd -

      - name: Run Script
        run: |
          git config --global init.defaultbranch main
          git config --global advice.detachedhead false
          curl -fsSL "${ScriptURL}" | bash
