name: Script Runner CI

on:
  workflow_dispatch:
    inputs:
      ScriptURL:
        description: "Script URL to Run"
        required: true
        type: string
      SkipTools:
        description: "Skip Tools Installation"
        type: boolean
        default: false
        required: false

env:
  ScriptURL: ${{ github.event.inputs.ScriptURL }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}

      - name: Checkout EncToolZ for Later Use
        if: github.event.inputs.SkipTools != 'true'
        env:
          RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
        run: |
          git config --global init.defaultbranch main
          git config --global advice.detachedhead false
          git clone --filter=blob:none --depth=1 https://github.com/ZeoRexDevs/EncToolZ ~/EncToolZ && rm -rf ~/EncToolZ/.git
          mkdir -p ~/.config/rclone && curl -fsSL --retry 5 --retry-connrefused --retry-delay 2 "${RCLONE_CONFIG_URL}" >~/.config/rclone/rclone.conf
          mkdir -p /tmp/service_accounts && git clone -q --filter=blob:none https://github.com/rokibhasansagar/RcloneSA4Phantom && mv RcloneSA4Phantom/accounts/*.json /tmp/service_accounts/ && rm -rf RcloneSA4Phantom
          export SAFileJSON=$(ls /tmp/service_accounts/*.json | shuf -n 1) && sed -i '/team_drive = 0AAjes57_d1IAUk9PVA/a service_account_file = '"${SAFileJSON}"'' ~/.config/rclone/rclone.conf
          # export PATH and LD_LIBRARY_PATH along with EncToolZ binaries on next step

      - name: Run Script
        run: |
          curl -fsSL "${ScriptURL}" | bash
