name: Script Runner CI

on:
  workflow_dispatch:
    inputs:
      RunnerMachine:
        description: "Runner Machine"
        required: true
        default: "ubuntu-22.04"
        type: choice
        options:
        - ubuntu-22.04
        - ubuntu-20.04
      ScriptURL:
        description: "Script URL to Run"
        required: true
        type: string
      RunAsRoot:
        description: "Run As Root?"
        type: boolean
        default: false
        required: false
      CleanWS:
        description: "Clean Workspace with slimhub_actions"
        type: boolean
        default: false
        required: false
      SkipTools:
        description: "Skip Tools Installation"
        type: boolean
        default: true
        required: false
      CustomEnvs:
        description: "Custom Env Vars (pipe-separated), x=a|y=2"
        type: string
        required: false

env:
  ScriptURL: ${{ github.event.inputs.ScriptURL }}
  CustomEnvs: ${{ github.event.inputs.CustomEnvs }}

jobs:
  build:
    runs-on: ${{ github.event.inputs.RunnerMachine }}

    steps:
      - uses: actions/checkout@v3

      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}

      - name: Use slimhub_actions
        if: github.event.inputs.CleanWS == 'true'
        uses: rokibhasansagar/slimhub_actions@main

      - name: Checkout EncToolZ for Later Use
        if: github.event.inputs.SkipTools != 'true'
        env:
          RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
        run: |
          git config --global init.defaultbranch main
          git config --global advice.detachedhead false
          git clone --filter=blob:none --depth=1 https://github.com/ZeoRexDevs/EncToolZ ~/EncToolZ && rm -rf ~/EncToolZ/.git
          mkdir -p ~/.config/rclone && curl -fsSL --retry 5 --retry-connrefused --retry-delay 2 "${RCLONE_CONFIG_URL}" >~/.config/rclone/rclone.conf
          mkdir -p /tmp/service_accounts && git clone -q --filter=blob:none https://github.com/rokibhasansagar/RcloneSA4Phantom && mv RcloneSA4Phantom/accounts/*.json /tmp/service_accounts/ && rm -rf RcloneSA4Phantom
          export SAFileJSON=$(ls /tmp/service_accounts/*.json | shuf -n 1) && sed -i '/team_drive = 0AAjes57_d1IAUk9PVA/a service_account_file = '"${SAFileJSON}"'' ~/.config/rclone/rclone.conf
          # export PATH and LD_LIBRARY_PATH along with EncToolZ binaries on next step

      - name: Run Script
        run: |
          if [[ ${CustomEnvs} != '' ]]; then
            for i in $(sed 's/|/\n/g' <<<"${CustomEnvs}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(cut -d'=' -f2- <<<"${i}" | sed 's#"##g')
              echo $v="$w" && export $v=$w
            done
          fi
          unset v w 2>/dev/null || true
          if [[ ${RunAsRoot} == true ]]; then
            export executorPrefix="sudo"
          fi
          curl -fsSL "${ScriptURL}" | ${executorPrefix:-} bash
