name: CI for PH4NTOM

on:
  workflow_dispatch:

env:
  RCLONE_INSTALL_MIRROR: ${{ secrets.RCLONE_INSTALL_MIRROR }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
  # FTOOL_ARC_URL: ${{ secrets.FTOOL_ARC_URL }}
  FTOOL_ARC_URL2: ${{ secrets.FTOOL_ARC_URL2 }}

jobs:
  shell2miraculous:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          git_name: "fr3akyphantom01"
          git_email: "85096237+fr3akyphantom01@users.noreply.github.com"
          credential: "yes"
          git_cookies: "no"
      - name: SSH Keepalive
        uses: rokibhasansagar/custom_workflows/ssh_keepalive@main
      - name: Rclone and FF Setup
        continue-on-error: true
        run: |
          cd "$(mktemp -d)"
          wget -q "${FTOOL_ARC_URL2}" || curl -sL "${FTOOL_ARC_URL2}" -O
          tar -xJf ff*.tar.xz --strip-components 1
          rm -f bin/*play
          sudo mv bin/* /usr/local/bin/
          curl -sL "${RCLONE_INSTALL_MIRROR}" | sudo bash
          mkdir -p ~/.config/rclone
          curl -sL "${RCLONE_CONFIG_URL}" >~/.config/rclone/rclone.conf
          python3 -m pip install -U yt-dlp
          cd -
      - name: Get S04 Files
        run: |
          # Cleanup Some Space
          sudo rm -rf /opt/hostedtoolcache/
          sudo rm -rf /usr/local/lib/android/sdk
          # Prepare Files for Series S04
          mkdir -p S04
          touch "Miraculous.Tales.of.Ladybug.and.Cat.Noir.S01EXX.1080p.Netflix.WEBRip.x264-TrollHD.txt"
          touch "Miraculous.Tales.of.Ladybug.and.Cat.Noir.S02EXX.1080p.Netflix.WEBRip.x264-TrollHD.txt"
          touch "Miraculous.Tales.of.Ladybug.and.Cat.Noir.S03EXX.1080p.Netflix.WEBRip.x264-NTb.txt"
          touch "Miraculous.Tales.of.Ladybug.and.Cat.Noir.S04EXX.1080p.Hulu.WEBRip.x264-LADYBUG.txt"
          cd S04/
          rclone copy td:/MiraculouSauce/Special/Sp0Shanghai/Miraculous.World.Shanghai.the.Legend.of.Lady.Dragon.2021.1080p.Hulu.WEBRip.x264-LAZY.mkv .
          mediainfo *.mkv
          ffprobe -hide_banner -y -i *.mkv
          for i in {2..12}; do
            sleep ${i} && echo
          done &
          ffprobe -hide_banner -loglevel warning -threads 4 -select_streams v -show_frames \
            -show_entries frame=pict_type -of csv *.mkv | grep -n I | cut -d ':' -f 1
          exit
      - name: NGROK Session
        continue-on-error: true
        run: curl -sL https://git.io/ngrok2actions4fr3aky.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: eu
          SSH_PASSWORD: SECRET
          TELEGRAM_BOT_TOKEN: ${{ secrets.NGBOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.NGBOT_CHAT }}
          REPO_PURPOSE: "Miraculous SSH Runner"
      - name: Empty
        continue-on-error: true
        timeout-minutes: 95
        run: |
          until [[ "${TIME_LEFT:=90}" = 0 ]]; do
            printf "Please wait %s Minute(s) ...\n" "${TIME_LEFT}"
            sleep 1m
            TIME_LEFT=$((TIME_LEFT - 1))
          done
          printf "You have 3 minutes 59 seconds left.\n"
          sleep 4m
          exit
