name: EncToolZ Updater

on:
  schedule:
    # Runs at 01:00 UTC on roughly every 5th day of every month
    - cron: '0 1 2,7,12,17,22,27 1-12 ?'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
        with:
          ref: main
          show-progress: false
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Update EncToolZ
        run: |
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/4e2498d9b09b46695aa759f1c800c4f1/" | grep "/UpdateEncToolZ\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          curl -fsSL "https://gist.github.com/rokibhasansagar/4e2498d9b09b46695aa759f1c800c4f1/raw/${latestRevision}/UpdateEncToolZ.sh" | bash
