name: EncToolZ Updater CI

on:
  schedule:
    # Runs at 01:00 UTC on roughly every 4th day of every month
    - cron: '0 1 2,6,10,14,18,22,26,30 1-12 ?'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Update EncToolZ
        run: |
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/4e2498d9b09b46695aa759f1c800c4f1/" | grep "/UpdateEncToolZ\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          curl -fsSL "https://gist.github.com/rokibhasansagar/4e2498d9b09b46695aa759f1c800c4f1/raw/${latestRevision}/UpdateEncToolZ.sh" | bash
